apiVersion: v1
kind: ConfigMap
metadata:
  name: itams-app-backend-settings
  namespace: default
data:
  # Simple key-value pairs
  DB_HOST: "itams-rds-dev.cfggec0eaqza.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "itams_db"
  DB_USER: "itams_app"