name: Deploy Dev
on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:

  # ==========================================================
  # Frontend Docker Build and Push
  # ==========================================================

  frontend-build-docker:
    name: Build and Push Frontend
    environment: dev
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend Docker image
        working-directory: ./frontend
        run: |
          docker build \
            -t itams-frontend:${{ github.run_number }} \
            .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Tag Docker image
        run: |
          docker tag \
            itams-frontend:${{ github.run_number }} \
            public.ecr.aws/w3l7a2t4/itams-frontend:${{ github.run_number }}

      - name: Push image to ECR
        run: |
          docker push \
            public.ecr.aws/w3l7a2t4/itams-frontend:${{ github.run_number }}


  # ==========================================================
  # Backend Docker Build and Push
  # ==========================================================

  backend-build-docker:
    name: Build and Push Backend
    environment: dev
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        working-directory: ./backend
        run: |
          docker build \
            -t itams-backend:${{ github.run_number }} \
            .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Tag Docker image
        run: |
          docker tag \
            itams-backend:${{ github.run_number }} \
            public.ecr.aws/w3l7a2t4/itams-backend:${{ github.run_number }}

      - name: Push image to ECR
        run: |
          docker push \
            public.ecr.aws/w3l7a2t4/itams-backend:${{ github.run_number }}

  #===========================================
  #deploy-app
  #=========================================
  backend-deploy:
    name: deploy Backend
    environment: dev
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: backend-deplpy
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      
      - name: Verify connection to cluster
        run: kubectl cluster-info

      - name: backend
        working-directory: ./backend
        run: |
          kubectl apply -f k8s 
      
      - name: frontend
        working-directory: ./frontend
        run: |
          kubectl apply -f k8s
      
      - name: Update application image for frontend
        run: |
           kubectl set image deployment/itams-frontend \
           itams-app-frontend=public.ecr.aws/w3l7a2t4/itams-frontend:${{ github.run_number }}

      - name: Update application image for backend
        run: |
           kubectl set image deployment/itams-backend \
           itams-app-backend=public.ecr.aws/w3l7a2t4/itams-backend:${{ github.run_number }}

      - name: check frontend deployment status
        run: kubectl rollout status deployment/itams-frontend --timeout=5m

      - name: check backend deployment status
        run: kubectl rollout status deployment/itams-backend --timeout=5m
      